# Generated by Django 5.2.16 on 2026-08-04 01:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name_ja', models.CharField(max_length=120)),
                ('name_ko', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('jlpt_level', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('draft', '초안'), ('reviewed', '관리자 검증')], default='draft', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('avatar_url', models.URLField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_ja', models.TextField()),
                ('translation_ko', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.grammar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_scope', models.CharField(choices=[('global', '공용 캐시'), ('private', '개인 캐시')], default='global', max_length=10)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('text_hash', models.CharField(max_length=64)),
                ('language', models.CharField(default='ja', max_length=8)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MorphologicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzer', models.CharField(default='SudachiPy', max_length=30)),
                ('analyzer_version', models.CharField(max_length=50)),
                ('dictionary_version', models.CharField(max_length=50)),
                ('split_mode', models.CharField(default='C', max_length=1)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphologies', to='core.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(default='sentence_analysis', max_length=30)),
                ('status', models.CharField(choices=[('queued', '대기'), ('running', '분석 중'), ('succeeded', '완료'), ('failed', '실패')], default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('admin', '관리자')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'AI 분석'), ('candidate', '가능한 문법'), ('reviewed', '관리자 검증'), ('failed', '실패')], default='draft', max_length=12)),
                ('meaning_ko', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('schema_version', models.CharField(default='1', max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.sentence')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.sentenceanalysis')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GrammarMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('method', models.CharField(choices=[('llm', 'LLM'), ('rule', '규칙'), ('admin', '관리자')], max_length=10)),
                ('evidence', models.TextField(blank=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentence_matches', to='core.grammar')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_matches', to='core.sentenceanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='SentencePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='core.sentenceanalysis')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='core.sentence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('context_before', models.TextField(blank=True)),
                ('context_after', models.TextField(blank=True)),
                ('saved_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sentenceanalysis')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_sentences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', '새 항목'), ('learning', '학습 중'), ('mastered', '숙달')], default='new', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('last_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.usersentence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tendency_type', models.CharField(choices=[('korean_expression', '한국어식 표현'), ('literal_translation', '직역 경향'), ('particle', '조사 사용'), ('tense', '시제'), ('other', '기타')], max_length=30)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('summary', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tendencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('queued', '대기'), ('analyzed', '분석 완료'), ('failed', '실패')], default='queued', max_length=10)),
                ('correctness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('naturalness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WritingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=50)),
                ('begin_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('explanation', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.writingsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('surface', models.CharField(max_length=255)),
                ('normalized_form', models.CharField(blank=True, max_length=255)),
                ('dictionary_form', models.CharField(blank=True, max_length=255)),
                ('reading_form', models.CharField(blank=True, max_length=255)),
                ('pos1', models.CharField(blank=True, max_length=50)),
                ('pos2', models.CharField(blank=True, max_length=50)),
                ('pos3', models.CharField(blank=True, max_length=50)),
                ('pos4', models.CharField(blank=True, max_length=50)),
                ('pos5', models.CharField(blank=True, max_length=50)),
                ('pos6', models.CharField(blank=True, max_length=50)),
                ('begin_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('morphology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.morphologicalanalysis')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('morphology', 'position'), name='unique_morpheme_position'), models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('begin_offset'))), name='morpheme_has_valid_offsets')],
            },
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(condition=models.Q(('cache_scope', 'global')), fields=('text_hash',), name='unique_global_sentence_hash'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(condition=models.Q(('cache_scope', 'private')), fields=('owner', 'text_hash'), name='unique_private_sentence_hash'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cache_scope', 'global'), ('owner__isnull', True)), models.Q(('cache_scope', 'private'), ('owner__isnull', False)), _connector='OR'), name='sentence_scope_has_valid_owner'),
        ),
        migrations.AddConstraint(
            model_name='morphologicalanalysis',
            constraint=models.UniqueConstraint(fields=('sentence', 'analyzer_version', 'dictionary_version', 'split_mode'), name='unique_morphology_version'),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('sentence', 'job_type'), name='unique_active_analysis_job'),
        ),
        migrations.AddConstraint(
            model_name='sentenceanalysis',
            constraint=models.UniqueConstraint(fields=('sentence', 'version'), name='unique_analysis_version'),
        ),
        migrations.AddConstraint(
            model_name='grammarmatch',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('begin_offset'))), name='grammar_match_has_valid_offsets'),
        ),
        migrations.AddConstraint(
            model_name='usersentence',
            constraint=models.UniqueConstraint(fields=('user', 'sentence'), name='unique_user_sentence'),
        ),
        migrations.AddConstraint(
            model_name='usertendency',
            constraint=models.UniqueConstraint(fields=('user', 'tendency_type'), name='unique_user_tendency'),
        ),
        migrations.AddConstraint(
            model_name='writingissue',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gte', models.F('begin_offset'))), name='writing_issue_has_valid_offsets'),
        ),
    ]
